[project]
name = "altpower"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["mpmath>=1.3.0", "numpy>=1.24", "matplotlib>=3.7"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
